### ISSUE TITLE
expose files

### ISSUE THREAD

**Issue by yoshokatana** [nymag/amphora#171]
Right now, our instances are looking deep into `@nymdev/amphora/lib/files` in our gulp scripts, because we need to get names / directories for components.

Move `files` up to services and expose them in the main entrypoint, so this becomes an actually-supported part of the module.

**Comment by TakenPilot** [comment]
Are `files` something people use our library for?

**Comment by yoshokatana** [comment]
Yeah. Gulp is using them to see where components are.

**Comment by TakenPilot** [comment]
That's not what I meant.  :p

Finding what components are available should probably be in the components' service, and if that's the only thing being used, we should just expose that.  People shouldn't be using our library to _read from files_ instead of the node `fs` library, I think.

**Comment by yoshokatana** [comment]
Yeah, agreed.
