### ISSUE TITLE
when scheduler runs, it doesn't generate page urls

### ISSUE THREAD

**Issue by yoshokatana** [nymag/amphora#187]
When a page is scheduled, and the scheduler gets around to publishing it, it doesn't do a PUT to `page@published` (but rather talks to db directly). This means our site-specific url generation doesn't run, and the publish fails with this error:

```
Unhandled rejection Error: Client: Page must have valid url to publish.
    at ~/amphora/lib/services/pages.js:172:13
```

This...makes sense, but maybe we should rethink how the scheduler calls publish.

**Comment by TakenPilot** [comment]
I think so too.  What are your thoughts?

**Comment by yoshokatana** [comment]
Per our discussion, Dane's gonna make amphora call `PUT /pages/whatever@published` rather than doing it internally

**Comment by yoshokatana** [comment]
fixed by https://github.com/nymag/amphora/pull/190
