### ISSUE TITLE
PUT to @published with no data should clone latest

### ISSUE THREAD

**Issue by yoshokatana** [nymag/amphora#202]
Idea: Sending a `PUT` to @published with no data should do a cascading PUT that clones the latest version of each component. This will allow us to publish layouts (and various components) really easily without having to manually GET and PUT the data for each individual component.

Extremely useful since we don't currently have a way in Kiln to publish layouts (or individual components)

**Comment by TakenPilot** [comment]
I like this idea, since the pages services supports it already (the `data` parameter is optional already).

**Comment by yoshokatana** [comment]
Yup :-)

**Comment by TakenPilot** [comment]
This is now in from https://github.com/nymag/amphora/releases/tag/v1.7.0
