### ISSUE TITLE
maybe bootstrap shouldn't overwrite db data?

### ISSUE THREAD

**Issue by yoshokatana** [nymag/amphora#203]
Right now, data in the bootstrap will overwrite corresponding data in the database. This is really useful for development and quick iteration when we don't know what the data structure will look like, but has become a bit of an issue with the actual sites.

Since we're currently specifying ALL layout-level components in the site bootstraps (because kiln doesn't have a UI around editing layouts directly, or creating/choosing layouts for pages), any user-added stuff in the layouts (sidebar components, etc) get wiped out every time we deploy our code to the servers.

Should we change it so that the db takes precedence over the bootstrap files? Or should we make kiln UI stuff a higher priority. It's definitely weird that we have _actual, production data_ in our bootstraps, and that seems like an unintended consequence of over-relying on them during development.

**Comment by gloddy** [comment]
That would match our original plan around an import.js script: Don't import if the data in question already exist. So, likewise, don't bootstrap if any data already exists or similar data already exists?

**Comment by yoshokatana** [comment]
Maybe. It would make development more difficult though (since you'd have to kill the db to change those values, or update them manually). As I wrote that I realized how weird it is that we have actual production data in our bootstrap, which I don't like.

On the other hand, most of us are simply using the in-memory db for local development anyways, so killing the db every time is already happening. Hmm...

**Comment by gloddy** [comment]
Perhaps a preference in the bootstrap itself as to whether it run based on either:
1. Whether data already exists
2. The current environment
?

**Comment by gloddy** [comment]
Dane rightly gave me the stink-eye on env-decedent behavior, so scratch that.

**Comment by gloddy** [comment]
After much slack chit-chat, it's clear that bootstrap, since it was a temporary measure, just needs to be retired. I'll push hard for the UX path on layout data and we'll go from there.

**Comment by yoshokatana** [comment]
I think that's the best way forward. The bootstrap is really nice for local development and testing with specific data, but we shouldn't be using it as a crutch for populating the database with real data.
