### ISSUE TITLE
Params for component endpoint?

### ISSUE THREAD

**Issue by ughitsaaron** [nymag/amphora#284]
Would it be useful to add optional params to our component endpoint that would add values to component properties to simplify testing, e.g., `/components/some-component?title=foo&url=http://google.com` would return component data with the `title` and `url` properties assigned with their respective values. `/components/some-component.html?title=foo&url=http://google.com` would return a rendered template with those values populated.

This can be accomplished with an instance into the components bootstrap, but this would make it easier for designers to test how components render with different data without having to create new instances in Kiln or without developers having to merge test instances of a component into the component's bootstrap.

**Comment by cruzanmo** [comment]
hmm, that could be useful, especially if a dev wanted to send a preview link to a designer. Although, in edit-mode a designer can change the settings and see how it renders.

It might be nice to allow edit-mode on a component, i.e. `/components/some-component/instances/0.html?edit=true`

**Comment by yoshokatana** [comment]
👎  if you want to test components, it's very easy to bootstrap data and instances

**Comment by ughitsaaron** [comment]
The issue with adding instances in a component bootstrap is that (for the moment, at least) those temporary test instances have to be merged into master to be viewable in our QA environment. Something like this would allow designers a way to view how a component renders without having to interact with scratch or manually sending a PUT.

I guess I'm wondering if there wouldn't be a benefit to being able to view a component with given data without having to write that data to the database.

**Comment by yoshokatana** [comment]
`scratch bootstrap http://qa.nymag.com/whatever ./path/to/test/data.yml`

**Comment by cruzanmo** [comment]
Instances are cheap. @ughitsaaron, the only danger I could see is if you overwrite data that is being used on a live page.

I do think it would be nice to be able to edit an individual component instance using an editor like clay-kiln, so design could play around with the settings.

**Comment by yoshokatana** [comment]
This was a consideration when we initially laid out how amphora, clay components, and server-side js would work, and we decided that bootstraps won over passing in data for a few reasons:

* they can be saved and shared between different people easily (especially for more complicated configs)
* that test data _should_ be preserved, so we can run automated and manual tests against it
* we don't have to worry about JSONification in query strings
* components (and amphora) _do things_ in server-side scripts that we wouldn't be able to deal with if we were passing in data on the GET

**Comment by yoshokatana** [comment]
@cruzanmo as for editing individual components, we've built tools to do that over and over and in practice nobody has ever used them. See: sandbox.

**Comment by ughitsaaron** [comment]
Word. This makes sense.

**Comment by ughitsaaron** [comment]
Okay, this makes sense. Closing.

**Comment by cruzanmo** [comment]
@yoshokatana sandbox was used but was not maintained over time as our systems quickly evolved. I agree it is not an essential feature.
