### ISSUE TITLE
When requesting a page by its URL the `data-uri` of the layout is replaced by a reference to the page's uri

### ISSUE THREAD

**Issue by byronhulcher** [nymag/amphora#316]
# Problem

When I request a page via its url (http://nymag.com/thecut/2016/10/janet-jackson-is-having-a-baby.html) then the data-uri of the top-most element will always be the page uri, and never the level of the top-level component, which is the layout.  This means that the layout uri is not surfaced in the rendered page, whereas the uri for all other components are.
### Why?

This is a consequence of the "page" not having its own top-level element to fit its data-uri into.  Instead, it replaces the data-uri of the layout element.  Every component must have a single top-level element, and in layout cases that is the html element.  You can't get more top-level than that!   
### Background

By design, data-uri can represents two things:
1) the URI of what you have (GET) requested (this data-uri will be located in the top-most element of the response)
2) the URI of an embedded component (composed using amphora!)

When you request a page via its url, for instance, http://nymag.com/thecut/2016/10/janet-jackson-is-having-a-baby.html then the data-uri of the top-most element will be the uri for the page (in this instance `nymag.com/thecut/pages/ciu72hr94003tt8y6czpothd1@published`)

When you request a page via its uri, you are able to get the layout used by the page.  For instance http://nymag.com/thecut/pages/ciu72hr94003tt8y6czpothd1@published yields the uri `nymag.com/thecut/components/layout/instances/article@published`

If you request a layout via its `.html` url (http://nymag.com/thecut/components/layout/instances/article@published.html) then the data-uri of the top-most element will be the uri of the layout (`nymag.com/thecut/components/layout/instances/article@published`)
# Some possible solutions
## 1) Multiple `data-*` attributes for uris

The templates for every component would contain two data-\* attributes at their top-most element, a `data-uri` and a `data-component-uri`.  `data-component-uri` would always be the uri to the component being rendered.  When a component is embedded, `data-uri` would ALSO be the uri to the component being rendered. When rendering a page instead of an individual component, the `data-uri` of the top-most component (the layout) would instead be the uri of the page
### Concerns

For the majority of components (N-1 components where N is the total number of components on the page) `data-uri` and `data-component-uri` would have the same data.
## 2) Re-name `data-uri` to `data-component-uri`, dynamically insert a `data-uri` at the top

Again, `data-component-uri` would ALWAYS contain the uri of the component.  `data-uri` would no longer be a part of a template, but would be automatically inserted at render time by amphora into the top-most element of whatever is being rendered, whether it is a page via url, a page via uri, or a layout or other component by its uri.  
### Concerns

This breaks a current rule of amphora that amphora will never modify a template that it is rendering.  
## 3) Give pages their own top-level element

We could give pages their own template with a top-level element, specifically, the `<html>` element.  The `data-uri` for that element work would as normally.  However, we'd have to split layouts in two (like they are on the factory) with seperate components for the `<head>` element and `<body>` elements.  Pages would then require both a `headLayout` and `bodyLayout` reference.
### Concerns

This is a VERY breaking change.  For our current implementation in sites, it would require us to do a data migration of EVERY page.

**Comment by cruzanmo** [comment]
A fourth solution would be to have the page uri in a `data-page-uri` attribute at the top level of the layout component; then the `data-uri` would always be the uri of the component.

**Comment by nelsonpecora** [comment]
After some discussion, the PR referenced above seems to be working nicely
