### ISSUE TITLE
Amphora Plugins

### ISSUE THREAD

**Issue by jonwinton** [nymag/amphora#386]
This has come up regarding features like the 'page-list' in Kiln. Amphora should not be responsible for updating an Elastic index, but we do want to easily hook into different stages of the Amphora lifecycle to keep external services in sync. 

Plugins must be registered in the app at Amphora instantiation (1) and expose hooks that Amphora can call (2).

Hooks:
- init
- save
- delete
- ???

**Comment by jonwinton** [comment]
First pass at implementation: https://github.com/nymag/amphora/commit/b33974c2d78e31851dfc5d5780f32dfea42d59cf

Needs tests and comments

**Comment by jonwinton** [comment]
Some plugins may want to query the database to resolve data for components, how should they do this? Should Amphora pass along a reference to the DB service to plugins at initialization? Should the plugins be required to connect to the DB on their own?

**Comment by amycheng** [comment]
I think Amphora should pass along a reference to the DB service. What's happening with `sites/services/db`? Would that be deprecated with plugins or has it already been deprecated because of the pubsub stuff and the new `model.js` conventions (ie avoiding using the db service)?

I also think that its a better separation of concerns if app/plugins avoid interacting with the DB directly; all of that should be delegated to Amphora.

**Comment by cperryk** [comment]
The [clay-sitemaps-generator](https://github.com/nymag/clay-sitemaps) I built is basically an Amphora plugin. Although we'll probably refactor this to rely less on Amphora and more on ElasticSearch at some point, it gives us some sense of what a plugin might need to do. Here's some of the stuff it does:

* Stream page objects from the database matching a prefix.
* Composes (or "explodes" or whatever) pages.
* Renders pages.
* Renders component instances.
* Transforms component/page URIs into other things -- e.g. into component names, instance names, swap versions, etc.

I agree with @amycheng -- I suspect reading Amphora data would be a pretty common task and it shouldn't be the concern of a plugin to implement a way to do that.

Somewhat tangential, but, on that last bullet point: We have many "turn page/cmpt URI into something else" utility functions across our systems ([here](https://github.com/nymag/sites/blob/master/services/db.js) [here](https://github.com/nymag/sites/blob/master/global/kiln-js/references.js) [here](https://github.com/nymag/clay-kiln/blob/master/services/references.js) [here](https://github.com/nymag/homepage-bot/blob/master/lib/components.js)). We should build a `clay-references` package that Amphora and everything else uses to do this kind of work.

**Comment by jonwinton** [comment]
@cperryk yeah, we've got a package in mind for parsing uris and whatnot. 

Those use cases are good to know of for the sitemap generator, and we're going to need to look at that soon to see how it fits in with the new Amphora architecture. I also see from the codebase that it adds a couple endpoints to the Express instance, so there's a lot going on.

I'll follow up with changes that need to happen to that repo once the renderer API and plugin API are solidified, but that looks like a nicely complex use case.

**Comment by jonwinton** [comment]
The current solution: if you need a reference to anything (like the DB), then pass it into a plugin in its own initialization _before_ you startup Amphora. This works and is nice because then all Amphora does is call hooks for plugins after registry.

**Comment by jonwinton** [comment]
Implementing in v2. 

Hooks:

- [ ] init
- [ ] save
- [ ] delete
- [ ] Unpublish

**Comment by jonwinton** [comment]
First pass resolved 👍
